### ISSUE TITLE
manifest-decrediton-v1.4.0.txt.asc is borked

### ISSUE THREAD

**Issue by al-maisan** [decred/decred-binaries#106]
It has the same content as manifest-decrediton-v1.4.0.txt

> manifests $ pwd
> /home/user/bin/decred-binaries/manifests
> manifests $ diff -u manifest-decrediton-v1.4.0.txt*
> manifests $ echo $?
> 0

**Comment by jrick** [comment]
The signature in the repo is wrong (and is instead is the manifest file itself, as you note).

The files attached to the GitHub release are clearly different because they have different sizes:

![screen shot 2019-02-13 at 8 47 29 pm](https://user-images.githubusercontent.com/1420313/52756860-c0735e00-2fd0-11e9-9cf8-08ac99fdc0c9.png)

cc @alexlyp

**Comment by alexlyp** [comment]
Yup looks like I borked it when I copied it over.  Fixing now.
