### ISSUE TITLE
Decredition v1.3.1 (and 1.3.0) blockchain sync on startup stalls / stuck

### ISSUE THREAD

**Issue by cryptostevo** [decred/decred-binaries#111]
Upon startup the 1.3.0 version would get stuck at Blockchain Syncing 342913/366181
I upgraded to 1.3.1 and the same result occurred.

**Comment by jrick** [comment]
You are forked off the network because you did not upgrade for the activation of [DCP0004](https://github.com/decred/dcps/blob/master/dcp-0004/dcp-0004.mediawiki).

If you were using full node syncing (as opposed to SPV syncing), that block is now permanently recorded as invalid in the DB, and you will have to delete it to resync.

This is also the wrong repository to open these issues.

**Comment by cryptostevo** [comment]
Thanks, where should I go to find more help on it?

**Comment by davecgh** [comment]
See the thread stickied at the top of the Decred reddit.

https://www.reddit.com/r/decred/comments/bnep6p/if_you_were_running_decrediton_at_13_or_earlier/
