### ISSUE TITLE
resolve difference in packaging of sample configurations

### ISSUE THREAD

**Issue by raedah** [decred/decred-binaries#80]
Currently the sample files for dcrctl and dcrwallet are included with the release files but the sample file for dcrd is not. dcrd goes about it a different way, generating its own default sample configuration when creating the initial .dcrd directory. 

The expected behavior is for the decred project to have a single agreed way to deliver the sample files to the users.

https://github.com/decred/dcrd/blob/master/sampleconfig/sampleconfig.go

https://github.com/decred/dcrd/blob/master/cmd/dcrctl/sample-dcrctl.conf

https://github.com/decred/dcrwallet/blob/master/sample-dcrwallet.conf

**Comment by xaur** [comment]
One convenience with separate .conf files was that I could inspect and adjust them before first launch.

Another is that I could diff my effective confs with sample confs to remember what I changed.

Now extra dance is necessary to get the default (sample) conf, like extracting it from git or re-generating it with dcrd using empty conf dir.

**Comment by xaur** [comment]
For history, I think this was first fixed in the `release` tool [commit c06d180](https://github.com/decred/release/commit/c06d180d6e1d90753e9a97ca49da860ce400b914) (2019-11-18) and the end users got it in the [v1.5.0 release](https://github.com/decred/decred-binaries/releases/tag/v1.5.0) (2019-12-16).
